### ISSUE TITLE
Will there be LiDAR data for the dataset?

### ISSUE THREAD

**Issue by haiphamcse** [wayveai/wayve_scenes#2]
Hi there, first of all thank you for the wonderful job of releasing the dataset! 
I want to ask whether the dataset contains LiDAR data and whether it will be released? As LiDAR is crucial for methods such as EmerNeRF to work, i think it is critical to have this in the dataset.

**Comment by jzuern** [comment]
Hi @haiphamcse, thanks for your interest in the dataset! 
LiDAR is not contained in the dataset. However, you could leverage depth estimation from RGB images if you need additional depth supervision for certain models.
