### ISSUE TITLE
About Camera Poses

### ISSUE THREAD

**Issue by starcraftvs** [wayveai/wayve_scenes#4]
Hi, I try to find the pose of camera when car in origin as mentioned in the Readme.md "We also provide metric camera poses in data/camera_transforms.json" but I can not find this file. Any advice?

**Comment by jzuern** [comment]
Hi @starcraftvs, thanks for your interest in the dataset! I just updated the description in the `README` file. We provide the metric distances from all cameras to the `ff` camera in the `data/baselines.json` file. Let me know if this helps or what else we can do to help with your use-case.

**Comment by jzuern** [comment]
I am closing this for now. Feel free to reopen 🙂
