### ISSUE TITLE
Camera Extrinsics in the Ego Frame

### ISSUE THREAD

**Issue by BenQLange** [wayveai/wayve_scenes#5]
Hi, thank you for releasing this dataset! 

How can I extract the cameras' extrinsics in the ego frame?

**Comment by jzuern** [comment]
Hey @BenQLange, thanks for your interest in the dataset!

We store the camera extrinsics inside our WayveScene object after loading the scene colmap data from disk. Please take a look at the following snippet:

```python
wayve_scene = WayveScene()
SCENE_DIR = "/path/to/wayve_scenes_101/scene_001"
COLMAP_PATH = os.path.join(SCENE_DIR, "colmap_sparse", "rig")
wayve_scene.read_colmap_data(Path(COLMAP_PATH), load_points_camera=False)
```

`wayve_scene.record["g_world_cam"]` should now contain the all camera poses for the scene in the world coordinate frame. It should be straightforward now to get the relative transformations between pairs of cameras. Is this what you were asking for?

**Comment by BenQLange** [comment]
Thanks!
